#!/bin/sh
#----------------------------------------------------------------------------------------------------
# Conventional commits enforcement hook
#----------------------------------------------------------------------------------------------------

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")
pattern="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert): .{1,50}"

if ! echo "$commit_msg" | grep -qE "$pattern"; then
  echo "Error: Commit message does not follow Conventional Commits format."
  echo "Format: <type>: <subject>"
  echo "Example: feat: add new feature"
  exit 1
fi
